name: 'Tweet testing'
on: workflow_dispatch

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        id: tweet
        uses: snow-actions/tweet@v1.1.1
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
#           status: |
#             Released ${{ github.event.release.name }}
#             ${{ github.event.release.html_url }}
          status: Just testing
#           media_paths: |
#             1st.png
#             2nd.png

      - run: echo ${{ steps.tweet.outputs.response }}
